<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes,viewport-fit=cover">
<meta name="format-detection" content="telephone=no, address=no, email=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="Author" content="">
<meta name="Keywords" content="">
<meta name="description" content="">
<title>문자/메일 발송시스템</title>
<link rel="icon" href="/html/sending/assets/image/favicon.ico">
<link type="text/css" rel="stylesheet" href="/html/sending/assets/css/slick.css">
<link type="text/css" rel="stylesheet" href="/html/sending/assets/css/jquery-ui.min.css">
<link type="text/css" rel="stylesheet" href="/html/sending/assets/css/common.css">
<script type="text/javascript" src="/html/sending/assets/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="/html/sending/assets/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/html/sending/assets/js/slick.min.js"></script>
<script type="text/javascript" src="/html/sending/assets/js/jquery.rwdImageMaps.js"></script>
<script type="text/javascript" src="/html/sending/assets/js/common.js"></script>
</head>
<body>
    <div class="wrap">
        <header id="header">
            <h1 class="header-logo"><a href="/html/sending/"><img src="/html/sending/assets/image/h1_logo.png" alt="M2"></a></h1>
            <ul class="gnb">
                <li>
                    <a href="/html/sending/html/member/list.html">
                        <span class="icon"></span>
                        대상자 관리
                    </a>
                </li>
                <li>
                    <a href="/html/sending/html/sms/list.html">
                        <span class="icon"></span>
                        문자 발송
                    </a>
                </li>
                <li>
                    <a href="/html/sending/html/mail/list.html">
                        <span class="icon"></span>
                        메일 발송
                    </a>
                </li>
                <li>
                    <a href="/html/sending/html/statistics/list_sms.html">
                        <span class="icon"></span>
                        통계
                    </a>
                </li>
            </ul>
            <a href="#n" class="btn btn-logout">
                <span class="icon"></span>
                LOGOUT
            </a>
        </header>