        <footer id="footer">
            <button type="button" class="btn-top js-btn-top">
                <img src="/assets/image/common/ic_top.png" alt="">
            </button>
            <div class="footer-wrap inner-layer">
                <div class="footer-con">
                    <strong class="tit">
                        <span>Contact Information</span>
                        <span>Congress Team</span>
                    </strong>
                    <ul>
                        <li>E. <a href="mailto:info@icop2025.org" target="_blank">info@icop2025.org</a></li>
                        <li>P. <a href="tel:+82-2-6959-5333" target="_blank">+82-2-6959-5333</a></li>
                        <li>F. +82-2-70-8677-6333</li>
                    </ul>
                </div>
                <strong class="footer-logo">
                    <img src="/assets/image/common/footer_logo.png" alt="ICOP SEOUL, KOREA, 2025.">
                </strong>
            </div>
            <p class="copy">
                Copyright &copy; ICOP 2025. All Rights Reserved.
            </p>
        </footer>
    </div>
</body>
</html>
