<footer id="footer">
    <button type="button" class="btn-top js-btn-top">
        <img src="/assets/image/common/ic_top.png" alt="">
    </button>
    <div class="footer-wrap inner-layer">
        <strong class="footer-logo">
            <img src="/assets/image/common/footer_logo02.png" alt="한국원생생물학회. The Korean Society of Protistologists">
        </strong>
        <div class="footer-con">
            <strong class="tit">
                The Korean Society of Protistologists
            </strong>
            <ul>
                <li>#251, 50-1, Yonsei-ro, Seodaemun-gu, Seoul, Republic of Korea</li>
                <li>TEL: <a href="tel:+82-2-446-6123" target="_blank">+82-2-446-6123</a></li>
                <li>
                    Business Registration No.: 226-82-70216 | Name of Representative: Mann Kyoon Shin
                </li>
            </ul>

            <strong class="tit">
                Congress Team
            </strong>
            <ul>
                <li>E-Mail: <a href="mailto:icop2025org@gmail.com" target="_blank">icop2025org@gmail.com</a></li>
            </ul>
        </div>
        <strong class="footer-logo">
            <img src="/assets/image/common/footer_logo.png" alt="ICOP SEOUL, KOREA, 2025.">
        </strong>
    </div>
    <p class="copy">
        Copyright &copy; ICOP 2025. All Rights Reserved.
    </p>
</footer>
</div>
</body>
</html>
