<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes,viewport-fit=cover">
<meta name="format-detection" content="telephone=no, address=no, email=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Expires" content="0">
<meta http-equiv="Pragma" content="no-cache">
<meta name="Author" content="ICOP/ISOP 2025">
<meta name="Keywords" content="ICOP/ISOP 2025">
<meta name="description" content="ICOP/ISOP 2025">
<title>ICOP/ISOP 2025</title>
<link rel="icon" href="/assets/image/favicon.ico">
<link type="text/css" rel="stylesheet" href="/assets/css/slick.css">
<link type="text/css" rel="stylesheet" href="/assets/css/jquery-ui.min.css">
<link type="text/css" rel="stylesheet" href="/assets/css/common.css">
<script type="text/javascript" src="/assets/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/assets/js/slick.min.js"></script>
<script type="text/javascript" src="/assets/js/jquery.rwdImageMaps.js"></script>
<script type="text/javascript" src="/assets/js/common.js"></script>
</head>

<body>
    <!-- 
        main일 때 calss="main"
        sub일 때 class="sub"
    -->
    <div class="wrap main">
        <header id="header" class="js-header">
            <div class="header-wrap inner-layer">
                <div class="dday-wrap">
                    <div class="dday-conbox">
                        <img src="/assets/image/common/ic_dday.png" alt="">
                        <div class="dday">
                            <strong>D-100</strong>
                            <span class="today">Today 2024-07-01</span>
                        </div>
                    </div>
                </div>
                <h1 class="header-logo">
                    <a href="/"><img src="/assets/image/common/h1_logo.png" alt="ICOP SEOUL, KOREA, 2025"></a>
                </h1>
                <div class="util-wrap">
                    <ul class="util-menu inner-layer-wide">
                        <li class="admin"><a href="#n">ADMIN</a></li>
                        <li class="home"><a href="/">HOME</a></li>
                        <li class="signup"><a href="#n">SIGN UP</a></li>
                        <li class="login"><a href="#n">LOGIN</a></li>
                        <!-- <li class="signup"><a href="#n">MY PAGE</a></li> -->
                    </ul>
                </div>
            </div>
            <nav id="gnb">
                <div class="gnb-wrap inner-layer">
                    <ul class="gnb js-gnb">
                        <li>
                            <a href="/html/about/overview.html">About the Congress</a>
                            <ul>
                                <li><a href="/html/about/overview.html">Overview</a></li>
                                <li><a href="/html/about/welcome.html">Welcome Message</a></li>
                                <li><a href="/html/about/society.html">About Society</a></li>
                                <li><a href="/html/about/committee.html">Committee</a></li>
                                <li><a href="/html/bbs/notice/list.html">Notice</a></li>
                                <li><a href="/html/about/contact.html">Contact Info</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n">Program <span class="new">N</span></a>
                            <ul>
                                <li><a href="#n">Program at a glance</a></li>
                                <li><a href="#n">Program in Detail</a></li>
                                <li><a href="#n">Plenary Lectures <span class="new">N</span></a></li>
                                <li><a href="#n">Invited Speakers</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n">Abstract</a>
                            <ul>
                                <li><a href="#n">Abstract Guidelines</a></li>
                                <li><a href="#n">Online Submission</a></li>
                                <li><a href="#n">Abstract Review & Modification</a></li>
                                <li><a href="#n">Presentation Guidelines</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n">Registration</a>
                            <ul>
                                <li><a href="#n">Registraion Guidelines</a></li>
                                <li><a href="#n">Go to Register</a></li>
                                <li><a href="#n">Registraion Confirmation and Receipt</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="/html/location/venue.html">Location</a>
                            <ul>
                                <li><a href="/html/location/venue.html">Venue</a></li>
                                <li><a href="/html/location/map.html">Map & Transportation <span class="new">N</span></a></li>
                                <li><a href="/html/location/accommodation.html">Accommodation</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>